//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Uyeler()
        {
            this.tbl_Begeniler = new HashSet<tbl_Begeniler>();
            this.tbl_Mesaj = new HashSet<tbl_Mesaj>();
            this.tbl_Mesaj1 = new HashSet<tbl_Mesaj>();
        }
    
        public int uyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public Nullable<decimal> enlem { get; set; }
        public Nullable<decimal> boylam { get; set; }
        public string sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Begeniler> tbl_Begeniler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mesaj> tbl_Mesaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mesaj> tbl_Mesaj1 { get; set; }
    }
}
