//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mesaj
    {
        public int mesajId { get; set; }
        public string mesajTxt { get; set; }
        public int aliciId { get; set; }
        public int gondericiId { get; set; }
    
        public virtual tbl_Uyeler tbl_Uyeler { get; set; }
        public virtual tbl_Uyeler tbl_Uyeler1 { get; set; }
    }
}
