//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UrunFotograflarİ
    {
        public int fotografId { get; set; }
        public string fotografAd { get; set; }
        public Nullable<int> urunId { get; set; }
    
        public virtual tbl_Urunler tbl_Urunler { get; set; }
    }
}
