//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Urunler()
        {
            this.tbl_Begeniler = new HashSet<tbl_Begeniler>();
            this.tbl_UrunFotograflarİ = new HashSet<tbl_UrunFotograflarİ>();
        }
    
        public int urunId { get; set; }
        public string urunAd { get; set; }
        public Nullable<int> tipId { get; set; }
        public Nullable<int> uyeId { get; set; }
        public Nullable<bool> urunDurumu { get; set; }
        public Nullable<System.DateTime> eklenmeTarihi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<bool> aktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Begeniler> tbl_Begeniler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UrunFotograflarİ> tbl_UrunFotograflarİ { get; set; }
        public virtual tbl_UrunTipi tbl_UrunTipi { get; set; }
    }
}
